# Generated by Django 6.0 on 2026-01-04 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('is_bot', models.BooleanField(default=False)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('established', models.PositiveIntegerField(blank=True, help_text='Year this node was established (e.g. 2019)', null=True)),
                ('name', models.CharField(max_length=100)),
                ('emoji', models.CharField(blank=True, max_length=10)),
                ('signup_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('timezone', models.CharField(default='UTC', help_text='e.g. Europe/Paris', max_length=50)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.group')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('question', models.CharField(max_length=500)),
                ('yes_count', models.PositiveIntegerField(default=0)),
                ('no_count', models.PositiveIntegerField(default=0)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.node')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('intros', 'Intros'), ('lunch', 'Lunch'), ('demos', 'Demos'), ('drinks', 'Drinks')], max_length=20)),
                ('time', models.TimeField(help_text='Time of day for this event')),
                ('where', models.CharField(blank=True, max_length=255)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.node')),
            ],
            options={
                'unique_together': {('node', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('date', models.DateTimeField()),
                ('text', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.group')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.person')),
            ],
            options={
                'unique_together': {('telegram_id', 'group')},
            },
        ),
        migrations.CreateModel(
            name='GroupPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('left', models.BooleanField(default=False)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.person')),
            ],
            options={
                'verbose_name': 'Group membership',
                'verbose_name_plural': 'Group memberships',
                'unique_together': {('group', 'person')},
            },
        ),
        migrations.CreateModel(
            name='ActivityDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.person')),
            ],
            options={
                'verbose_name': 'Activity day',
                'verbose_name_plural': 'Activity days',
                'unique_together': {('person', 'group', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PollAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yes', models.BooleanField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.person')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.poll')),
            ],
            options={
                'unique_together': {('poll', 'person')},
            },
        ),
    ]
