# Generated by Django 6.0 on 2026-01-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="privacy",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="person",
            name="username_x",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
