# Generated by Django 6.0 on 2026-01-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0002_person_privacy_person_username_x"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="onboarded",
            field=models.BooleanField(default=False),
        ),
    ]
