# Generated by Django 6.0 on 2026-01-04 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0003_add_onboarded_to_person"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="bio",
            field=models.TextField(blank=True),
        ),
    ]
