# Generated by Django 6.0 on 2026-01-04 11:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0004_person_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="node",
            name="slug",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True
            ),
        ),
    ]
