# Generated by Django 6.0 on 2026-01-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0005_node_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="last_reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="node",
            name="last_poll_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
