# Generated by Django 6.0 on 2026-01-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0006_event_last_reminder_sent_at_node_last_poll_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="last_weekly_summary_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
