# Generated by Django 6.0 on 2026-01-05 11:05

from datetime import time

from django.db import migrations

# Node data from swellbot/swellbot/apps/worker/hackabot.py and hacka.world
NODES_DATA = [
    dict(
        name="Hackagu",
        emoji="🇮🇩",
        telegram_chat_id=-1002187593598,
        location="Canggu, Bali",
        timezone="Asia/Makassar",
        established=2019,
        signup_url="https://hackagu.org",
        events=[
            dict(type="intros", time=time(9, 30)),
            dict(type="demos", time=time(16, 0)),
            dict(type="lunch", time=time(12, 30), where="Kiva Room"),
            dict(type="drinks", time=time(17, 0), where="Black Sands"),
        ],
    ),
    dict(
        name="Hackumvit",
        emoji="🇹🇭",
        telegram_chat_id=-1001973395541,
        location="Bangkok",
        timezone="Asia/Bangkok",
        established=2022,
        signup_url="https://hackumvit.com",
        events=[
            dict(type="intros", time=time(10, 30)),
            dict(type="demos", time=time(17, 0)),
        ],
    ),
    dict(
        name="Hackaditch",
        emoji="🇬🇧",
        telegram_chat_id=-1002092252344,
        location="Shoreditch, London",
        timezone="Europe/London",
        established=2024,
        signup_url="https://hackaditch.com",
        events=[
            dict(type="intros", time=time(10, 0)),
            dict(type="demos", time=time(16, 30)),
        ],
    ),
    dict(
        name="Hackamai",
        emoji="🇹🇭",
        telegram_chat_id=-1002345271386,
        location="Chiang Mai, Thailand",
        timezone="Asia/Bangkok",
        established=2024,
        signup_url="https://hackamai.com",
        events=[
            dict(type="intros", time=time(10, 30)),
            dict(type="demos", time=time(16, 30)),
        ],
    ),
    dict(
        name="Hackawatu",
        emoji="🇮🇩",
        telegram_chat_id=-1002402973203,
        location="Uluwatu, Bali",
        timezone="Asia/Makassar",
        established=2024,
        signup_url="https://hackawatu.com",
        events=[
            dict(type="intros", time=time(9, 30)),
            dict(type="demos", time=time(16, 0)),
        ],
    ),
    dict(
        name="Hackaigon",
        emoji="🇻🇳",
        telegram_chat_id=-1001837919607,
        location="Ho Chi Minh City, Vietnam",
        timezone="Asia/Ho_Chi_Minh",
        established=2024,
        signup_url="https://tally.so/r/mDJ2V5",
        events=[
            dict(type="intros", time=time(9, 30)),
            dict(type="demos", time=time(16, 0)),
        ],
    ),
    dict(
        name="Hackanang",
        emoji="🇻🇳",
        telegram_chat_id=-1002147178796,
        location="Da Nang, Vietnam",
        timezone="Asia/Ho_Chi_Minh",
        established=2025,
        signup_url="https://tally.so/r/3XXRbV",
        events=[
            dict(type="intros", time=time(10, 30)),
            dict(type="demos", time=time(16, 30)),
        ],
    ),
    dict(
        name="Hackaseoul",
        emoji="🇰🇷",
        telegram_chat_id=-1002862498601,
        location="Seoul",
        timezone="Asia/Seoul",
        established=2025,
        signup_url="https://hackaseoul.com",
        events=[
            dict(type="intros", time=time(9, 30)),
            dict(type="demos", time=time(16, 0)),
        ],
    ),
    dict(
        name="Hackaboa",
        emoji="🇵🇹",
        telegram_chat_id=-1003027086948,
        location="Lisbon",
        timezone="Europe/Lisbon",
        established=2025,
        signup_url="https://hackaboa.com",
        events=[
            dict(type="intros", time=time(9, 30)),
            dict(type="demos", time=time(16, 0)),
        ],
    ),
]


def populate_nodes(apps, schema_editor):
    Group = apps.get_model("bot", "Group")
    Node = apps.get_model("bot", "Node")
    Event = apps.get_model("bot", "Event")

    for node_data in NODES_DATA:
        group, _ = Group.objects.get_or_create(
            telegram_id=node_data["telegram_chat_id"],
            defaults=dict(display_name=node_data["name"]),
        )

        node, _ = Node.objects.get_or_create(
            name=node_data["name"],
            defaults=dict(
                group=group,
                emoji=node_data["emoji"],
                location=node_data["location"],
                timezone=node_data["timezone"],
                established=node_data["established"],
                signup_url=node_data["signup_url"],
            ),
        )

        for event_data in node_data["events"]:
            Event.objects.get_or_create(
                node=node,
                type=event_data["type"],
                defaults=dict(
                    time=event_data.get("time"),
                    where=event_data.get("where", ""),
                ),
            )


def reverse_populate_nodes(apps, schema_editor):
    Node = apps.get_model("bot", "Node")
    node_names = [n["name"] for n in NODES_DATA]
    Node.objects.filter(name__in=node_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0007_group_last_weekly_summary_sent_at"),
    ]

    operations = [
        migrations.RunPython(populate_nodes, reverse_populate_nodes),
    ]
