# Generated by Django 6.0 on 2026-01-07 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0008_populate_existing_nodes"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Message",
        ),
    ]
