# Generated by Django 6.0 on 2026-01-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
