# Generated by Django 6.0 on 2026-01-31 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_node_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetupPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_file_id', models.CharField(max_length=255, unique=True)),
                ('image_data', models.BinaryField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.node')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.person')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
