# Generated by Django 6.0 on 2026-01-31 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_meetupphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='event_day',
            field=models.PositiveSmallIntegerField(default=3, help_text='Day of week for events (0=Monday, 4=Friday, etc.)'),
        ),
        migrations.AlterField(
            model_name='meetupphoto',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
