# Generated by Django 6.0 on 2026-02-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_node_event_day_alter_meetupphoto_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='send_global_invite',
            field=models.BooleanField(default=True, help_text='Send global chat invite with weekly poll'),
        ),
    ]
