# Generated by Django 6.0 on 2026-03-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_node_send_global_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
