# Generated by Django 6.0 on 2026-04-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0014_add_message_id_to_poll"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="last_yearly_summary_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
