# Generated by Django 6.0 on 2026-05-28 07:48

from django.db import migrations, models


def backfill_is_attendance(apps, schema_editor):
    Poll = apps.get_model("bot", "Poll")
    Poll.objects.filter(message_id__isnull=False).update(is_attendance=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0016_node_unlisted"),
    ]

    operations = [
        migrations.AddField(
            model_name="poll",
            name="is_attendance",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_is_attendance, noop),
    ]
