# Generated by Django 6.0 on 2026-07-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0018_joinrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="joinrequest",
            name="admin_message_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="joinrequest",
            name="proof_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
