# Generated by Django 6.0 on 2026-07-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0019_joinrequest_admin_message_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="joinrequest",
            name="admin_message_id",
        ),
        migrations.AddField(
            model_name="joinrequest",
            name="admin_message_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
