# Generated by Django 6.0 on 2026-07-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0020_remove_joinrequest_admin_message_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="joinrequest",
            name="pending_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
