# Generated by Django 6.0 on 2026-07-08 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0021_joinrequest_pending_since"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupperson",
            name="welcomed",
            field=models.BooleanField(default=False),
        ),
    ]
